### ISSUE TITLE
Make launch error :  "PhysicsEngine/BodySetupEnums.h" not found

### ISSUE THREAD

**Issue by aakashsehgal** [carla-simulator/carla#4124]
Building Carla 0.9.11 on windows 10.
Unreal Engine 4.26
Python 3.7.9

Building the unreal engine succeeds.

While building the Carla server with make launch i receive an error  

> "C:/Tools/Carla/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/OpenDrive/OpenDriveGenerator.cpp(19): fatal error C1083: Cannot open include file: 'PhysicsEngine/BodySetupEnums.h': No such file or directory
> make: *** [CarlaUE4Editor] Error 6"
> 

I also checked in the` "C:\UnrealEngine\Engine\Source\Runtime\Engine\Private\PhysicsEngine"` but no such file `"BodySetupEnums.h"` is present. 

How can i get this file ?

**Comment by Axel1092** [comment]
Hi @aakashsehgal, you are building a version of carla that works with UE 4.24 and not 4.26, the errors you see are the result of the incompatibility. You need to switch to UE4.24.

**Comment by jbenzhhn** [comment]
I ran into the same problem because the https://carla.readthedocs.io/en/latest/ is made up for the next carla versino 0.9.12 (which is not released yet). Make sure to select the fitting carla version down below. 
![Wiki2](https://user-images.githubusercontent.com/82030917/115730382-8bb87980-a386-11eb-8d8a-a8f94690029d.PNG)

**Comment by aakashsehgal** [comment]
ok...so i need to shift to UE4.24 and Carla 0.9.11 right ?

**Comment by jbenzhhn** [comment]
Exactly :) For me it is working right now

**Comment by NikhilKalghatgi** [comment]
@jbenzhhn @aakashsehgal how do we shift to UE4.24? I am having a hard time doing that, please help here

**Comment by jbenzhhn** [comment]
Hi @NikhilKalghatgi ;) Remove the whole carla folder from your installation of latest build and just try to follow the  [carla wiki build instructions](https://carla.readthedocs.io/en/0.9.11/build_linux/) with the corresponding version. In the moment its carla 0.9.11.

**Comment by NikhilKalghatgi** [comment]
> Hi @NikhilKalghatgi ;) Remove the whole carla folder from your installation of latest build and just try to follow the [carla wiki build instructions](https://carla.readthedocs.io/en/0.9.11/build_linux/) with the corresponding version. In the moment its carla 0.9.11.

Thanks it worked :)

**Comment by ucbmpc2021** [comment]
Hi! @Axel1092  @jbenzhhn  I am building Carla 0.9.9 and using UE4.24. However I still got the exact same error. Any clue why this might happened? Much thanks!
