### ISSUE TITLE
get_level_bbs

### ISSUE THREAD

**Issue by pushkar4501** [carla-simulator/carla#5171]
CARLA version: 0.9.10
Platform/OS: Linux
Problem you have experienced: I am trying to use get_level_bbs to collect bounding box in the world. 
but error shows: 
global_vehicle_bbs = world.get_level_bbs(carla.CityObjectLabel.Vehicles)
AttributeError: 'World' object has no attribute 'get_level_bbs'

My question is does "get_level_bbs" work in carla version 0.9.10 and if yes, someone has example source code for it?
Thank you in advance

**Comment by Blackcipher101** [comment]
same issue
