### ISSUE TITLE
CARLA 0.9.14 Document needs to updated: AttributeError: type object 'CityObjectLabel' has no attribute 'Vehicles' 

### ISSUE THREAD

**Issue by yaodongC** [carla-simulator/carla#6216]

**Comment by yaodongC** [comment]
This happens in 0.9.14 only on both pre-compiled (downloaded from release) and compiled from source CARLA.
The same code works fine on 0.9.12 pre-compiled version.
Only carla.CityObjectLabel.Vehicles cause this problem, other labels such as get_environment_objects(carla.CityObjectLabel.Buildings) works fine in 0.9.14

System: Ubuntu 18
CARLA: 0.9.14 both pre-compiled and built from source

**Comment by yaodongC** [comment]
From the surce code, CityObjectLabel.Vehicles has changed to Cars, Trucks and Bus, which are good. But this change in semantic tags has not been reflected in the[ 0.9.14 document](https://carla.readthedocs.io/en/latest/python_api/#carla.CityObjectLabel).

**Comment by MattRoweEAIF** [comment]
This is now fixed, thanks for making an issue
