### ISSUE TITLE
error: no member named 'run_for' in 'boost::asio::io_service'

### ISSUE THREAD

**Issue by ChidanandKumarKS** [carla-simulator/carla#742]
While installing make launch, in installed the boost.. Kindly suggest

i got the error below:

In file included from ../../LibCarla/source/test/test_rpc.cpp:11:
../../LibCarla/cmake/../source/carla/rpc/Server.h:103:24: error: no member named 'run_for' in 'boost::asio::io_service'
      _sync_io_service.run_for(duration.to_chrono());
      ~~~~~~~~~~~~~~~~ ^
1 error generated.

**Comment by iFuSiiOnzZ** [comment]
What version of boost are you using? I remember having the same problem and was because it was compiling a wrong version of boost, I was using 1.64 instead of 1.67, run_for it's available since [1.66](https://www.boost.org/doc/libs/1_66_0/doc/html/boost_asio/reference/io_service.html)

**Comment by ChidanandKumarKS** [comment]
I was working with 1.61.0 version of boost. Now iam starting with boost1.68.0 version...

**Comment by Savash2016** [comment]
hey guys,
I have the same probleme! :(
I already have installed  boost version 1.67
but I have the same. I hope someone can help me

**Comment by iFuSiiOnzZ** [comment]
Hi @Savash2016

With the version you are using it shouldn't happen. Can you explain how do you build Carla and which platform?

**Comment by Savash2016** [comment]
Hey @iFuSiiOnzZ 
first I install clang 5.0.0.
After this I Build Unreal Engine and I export some path (e.g. export UE4_ROOT).
At the end I download carla and do an Update.  
With "make launch" I start building carla. 

Everything works fine, until starting BuildLibCarla.sh.

I use CentOS 7

**Comment by iFuSiiOnzZ** [comment]
Unfortunately I can help you to much, I maintain the Windows build system and works slightly different from the Linux one. @nsubiron can help you more as he is in charge of the Linux build. Anyway if you know bash under `Utils\BuildTools\Setup.sh` is the script in charge of downloading and setting up boost. Sorry for not providing more useful information, try to confirm that when building is using the correct boost version.

**Comment by Savash2016** [comment]
@iFuSiiOnzZ 
Thank you. I'll keep trying. :)

**Comment by nsubiron** [comment]
The recommended way is using the setup script (`make` should do it automatically starting from 0.9.0). Not only downloads the right version of the dependencies, it also compiles them with `libc++` when necessary so they link with the same runtime library as Unreal.

**Comment by yaogang2018** [comment]
@Savash2016 Are you running `make launch` in conda environments? I run into same problem, but this issue #199 solves my probelm. It seems even if building Boost gets errors, the Setup.sh thinks Boost is installed, then problems occurs.

**Comment by Manojbhat09** [comment]
Hey guys @ChidanandKumarKS  i fixed it!
### SUCCESS

What i changed from setup.sh:
BOOST_BASENAME=boost-1.67.0

BOOST_INCLUDE=${PWD}/${BOOST_BASENAME}-install/include
BOOST_LIBPATH=${PWD}/${BOOST_BASENAME}-install/lib

if [[ -d "${BOOST_BASENAME}-install" ]] ; then
  log "${BOOST_BASENAME} already installed."
else

  rm -Rf ${BOOST_BASENAME}-source

  log "Retrieving boost."
  wget https://dl.bintray.com/boostorg/release/1.6.0/source/boost_1_67_0.tar.gz
  log "Extracting boost."
  tar -xzf boost_1_67_0.tar.gz
  rm boost_1_67_0.tar.gz
  mkdir -p ${BOOST_BASENAME}-install/include
  mv boost_1_67_0 ${BOOST_BASENAME}-source
  # rm -Rf boost_1_67_0

  pushd ${BOOST_BASENAME}-source >/dev/null

  BOOST_TOOLSET="clang-5.0"
  BOOST_CFLAGS="-fPIC -std=c++14 -DBOOST_ERROR_CODE_HEADER_ONLY"

  ./bootstrap.sh \
      --with-toolset=clang \
      --prefix=../boost-install \
      --with-libraries=python
  ./b2 clean
  ./b2 toolset="${BOOST_TOOLSET}" cxxflags="${BOOST_CFLAGS}" --prefix="../${BOOST_BASENAME}-install" -j 12 stage release
  ./b2 install toolset="${BOOST_TOOLSET}" cxxflags="${BOOST_CFLAGS}" --prefix="../${BOOST_BASENAME}-install" -j 12

  popd >/dev/null


to:
BOOST_BASENAME=boost-1.68.0

BOOST_INCLUDE=${PWD}/${BOOST_BASENAME}-install/include
BOOST_LIBPATH=${PWD}/${BOOST_BASENAME}-install/lib

if [[ -d "${BOOST_BASENAME}-install" ]] ; then
  log "${BOOST_BASENAME} already installed."
else

  rm -Rf ${BOOST_BASENAME}-source

  log "Retrieving boost."
  wget https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
  log "Extracting boost."
  tar -xzf boost_1_68_0.tar.gz
  rm boost_1_68_0.tar.gz
  mkdir -p ${BOOST_BASENAME}-install/include
  mv boost_1_68_0 ${BOOST_BASENAME}-source
  # rm -Rf boost_1_68_0

  pushd ${BOOST_BASENAME}-source >/dev/null

  BOOST_TOOLSET="clang-5.0"
  BOOST_CFLAGS="-fPIC -std=c++14 -DBOOST_ERROR_CODE_HEADER_ONLY"

  ./bootstrap.sh \
      --with-toolset=clang \
      --prefix=../boost-install \
      --with-libraries=python
  ./b2 clean
  ./b2 toolset="${BOOST_TOOLSET}" cxxflags="${BOOST_CFLAGS}" --prefix="../${BOOST_BASENAME}-install" -j 12 stage release
  ./b2 install toolset="${BOOST_TOOLSET}" cxxflags="${BOOST_CFLAGS}" --prefix="../${BOOST_BASENAME}-install" -j 12

  popd >/dev/null


and ran:
make LibCarla

It fixed itself 💯  :) :) :) 
I am so happy that i could after days :D XD
