### ISSUE TITLE
CARLA master branch build on Ubuntu 20.04 not working

### ISSUE THREAD

**Issue by rreddy78** [carla-simulator/carla#6105]
CARLA version: **master branch and release of CARLA**
Platform/OS: **Ubuntu 20.04**
Problem you have experienced: **make launch and make package is failing**
What you expected to happen: **build should have worked**
Steps to reproduce: **Latest CARLA master branch**
Other information (documentation you consulted, workarounds you tried): Latest UnrealEngine (carla branch).
I am following the instructions of the documentation: https://carla.readthedocs.io/en/latest/build_linux/#unreal-engine

UnrealEngine build succeeded.
make PythonAPI succeeded

make launch gave me this error first:

_Time Elapsed 00:00:01.98
Log file: /home/sxv1kor/Downloads/GitHub/UnrealEngine/Engine/Programs/UnrealBuildTool/Log_GPF.txt
Some Platforms were skipped due to invalid SDK setup: Android.
See the log file for detailed information
Discovering modules, targets and source code for project...
/home/sxv1kor/Downloads/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/CarlaTools.Build.cs(11,104): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'Win32'
/home/sxv1kor/Downloads/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs(14,104): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'Win32'
Expecting to find a type to be declared in a target rules named 'CarlaUE4Target'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
BuildCarlaUE4.sh: Build C_

If I try again, I get this error:

_make package and make launch not working
Discovering modules, targets and source code for project...
Compiled assembly file '/home/sxv1kor/Downloads/carla/Unreal/CarlaUE4/Intermediate/Build/BuildRules/CarlaUE4ModuleRules.dll' appears to be for a newer CLR version or is otherwise invalid.  Unreal Build Tool will try to recompile this assembly now.  (Exception: Bad IL format. The format of the file '/home/sxv1kor/Downloads/carla/Unreal/CarlaUE4/Intermediate/Build/BuildRules/CarlaUE4ModuleRules.dll' is invalid.)
/home/sxv1kor/Downloads/carla/Unreal/CarlaUE4/Plugins/CarlaTools/Source/CarlaTools/CarlaTools.Build.cs(11,104): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'Win32'
/home/sxv1kor/Downloads/carla/Unreal/CarlaUE4/Plugins/Carla/Source/Carla/Carla.Build.cs(14,104): error CS0117: 'UnrealTargetPlatform' does not contain a definition for 'Win32'
Expecting to find a type to be declared in a target rules named 'CarlaUE4Target'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool._

**Comment by rreddy78** [comment]
Why doesnt the build work with the given instructions ?

**Comment by rreddy78** [comment]
I see now why I get this error. I have not followed the build instructions..
Have used the UnrealEngine 5.1 (carla branch) instead of the fork for Carla 4.26 as given in docs!
